# Generated by Django 6.0.1 on 2026-01-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Course name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Batch/Class name')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50, verbose_name='Admission No')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('tamil_name', models.CharField(blank=True, max_length=200, verbose_name='Tamil name')),
                ('guardian_name', models.CharField(blank=True, max_length=200, verbose_name='Guardian name')),
                ('guardian_phone', models.CharField(blank=True, max_length=30, verbose_name='Guardian phone')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('current_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.batch')),
            ],
            options={
                'unique_together': {('branch', 'admission_no')},
            },
        ),
    ]
